# This is a basic workflow to help you get started with Actions

name: Bump version

# Controls when the workflow will run
on: 
  push:
    branches:
      - 'release-**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  versionup:
    runs-on: macos-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
        
      - name: Extract version
        run: echo "##[set-output name=version;]$(echo ${GITHUB_REF#refs/heads/release-})"
        id: marketing_version
        
      - name: Bump AmityUIKit version
        uses: yanamura/ios-bump-version@v1
        with:
          version: ${{ steps.marketing_version.outputs.version }}
          build-number: 1
          project-path: UpstraUIKit
          
      - name: Bump sample app version
        uses: yanamura/ios-bump-version@v1
        with:
          version: ${{ steps.marketing_version.outputs.version }}
          build-number: 1
          project-path: UpstraUIKit/SampleApp
  
  createPullRequest:
    runs-on: ubuntu-latest
    needs: versionup
    steps:
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with: 
          commit-message: Bump AmityUIKit version
          title: 'Release ${{ steps.marketing_version.outputs.version }}'
          branch: ${GITHUB_REF##*/}
          base: master
          body: |
            ### Issue:
            [ ] New Feature
            [ ] Bug Fix
            [ ] Breaking Changes
            [ ] Internal Improvements
            [x] Others
          draft: false
          delete-branch: true

