# This is a basic workflow to help you get started with Actions

name: Bump version

# Controls when the workflow will run
on: 
  push:
    branches:
      - 'release-**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  versionup:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
        
      - name: Extract version
        run: echo version from the branch is "::set-env name=MARKETING_VERSION::$(echo ${GITHUB_REF#refs/heads/release-})"
        
      - name: Bump version
        uses: yanamura/ios-bump-version@v1
        with:
          version: ${{ env.MARKETING_VERSION }}
          # build-number: ${{github.run_number}}
          project-path: UpstraUIKit/AmityUIKit.xcodeproj
          
      - name: Commit changes
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git add -A
          git commit -am "Bump AmityUIKit version"
          git push
