# This is a basic workflow to help you get started with Actions

name: Bump version

# Controls when the workflow will run
on: 
  push:
    branches:
      - 'release-**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  versionup:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
        
      - name: Extract version
        run: echo "##[set-output name=version;]$(echo ${GITHUB_REF#refs/heads/release-})"
        id: marketing_version
        
      - name: Bump AmityUIKit version
        uses: yanamura/ios-bump-version@v1
        with:
          version: ${{ steps.marketing_version.outputs.version }}
          project-path: UpstraUIKit
          
      - name: Bump sample app version
        uses: yanamura/ios-bump-version@v1
        with:
          version: ${{ steps.marketing_version.outputs.version }}
          project-path: UpstraUIKit/SampleApp
          
      - name: Commit changes
        run: |
          git add -A
          git commit -am "Bump AmityUIKit version"
          git push
