# This is a basic workflow to help you get started with Actions

name: Bump version

# Controls when the workflow will run
on: 
  push:
    branches:
      - 'release-**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  bumpversion:
    runs-on: macos-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
        
      - name: Extract version
        run: echo "##[set-output name=version;]$(echo ${GITHUB_REF#refs/heads/release-})"
        id: marketing_version
        
      - name: Bump AmityUIKit version
        uses: yanamura/ios-bump-version@v1
        with:
          version: ${{ steps.marketing_version.outputs.version }}
          build-number: 1
          project-path: UpstraUIKit
          
      - name: Bump sample app version
        uses: yanamura/ios-bump-version@v1
        with:
          version: ${{ steps.marketing_version.outputs.version }}
          build-number: 1
          project-path: UpstraUIKit/SampleApp
      
      - name: Commit changes
        run: |
          git config --global user.name "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
          git add -A
          git commit -am "Bump AmityUIKit version"
          git push
  
  createPullRequest:
    runs-on: ubuntu-latest
    needs: bumpversion
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        
      - name: Extract version
        run: echo "##[set-output name=version;]$(echo ${GITHUB_REF#refs/heads/release-})"
        id: marketing_version
        
      - name: Run the Action
        uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: master
          title: Release ${{ steps.marketing_version.outputs.version }}
          body: |
            ### Issue:
            - [ ] New Feature
            - [ ] Bug Fix
            - [ ] Breaking Changes
            - [ ] Internal Improvements
            - [x] Others
          label: ${{ steps.marketing_version.outputs.version }}
          draft: false
          allow_no_diff: false

